[[intro]]
== You Know, for Search...
[[intro]]
== You Know, for Search...

Elasticsearch 是一个开源的搜索引擎，建立在一个全文搜索引擎库 https://lucene.apache.org/core/[Apache Lucene(TM)] 基础之上。
((("Apache Lucene")))((("Lucene")))  Lucene 可能是目前存在的，不论开源还是私有的，拥有最新进，高性能和全功能搜索引擎功能的库

但是 Lucene 仅仅只是一个库。为了利用它，你需要编写 java 程序，并在你的 java 程序里面直接集成 Lucene 包。
更坏的情况是，你需要对信息检索有一定程度的理解才能明白 Lucene 是怎么工作的。Lucene 是 _很_ 复杂的。

Elasticsearch 也是使用 Java 编写的，它的内部使用 Lucene 做索引与搜索，但是它的目标是使全文检索变得简单，
通过隐藏 Lucene 的复杂性，取而代之的提供一套简单一致的 RESTful API。


然而，Elasticsearch 不仅仅是 Lucene，并且也不仅仅只是一个全文搜索引擎。((("Elasticsearch", "capabilities")))
它可以被下面这样准确的形容：

* 一个分布式的实时文档存储，_每个字段_ 可以被索引与搜索
* 一个分布式实时分析搜索引擎
* 能胜任上百个服务节点的扩展，并支持 PB 级别的结构化或者非结构化数据

并且它在一台单独的服务器上打包了所有的功能，这样你可以通过程序去访问简单的 RESTful API 服务，不论你是
使用自己喜欢的编程语言还是直接使用命令行（去充当这个客户端）。

就 Elasticsearch 而言，起步很简单。对于初学者来说，它预设了一些适当的默认值，并隐藏了复杂的搜索理论知识。
它 _开箱即用_。最小的理解，你不久就可以变得多产。((("Elasticsearch", "installing")))

随着你知识的积累，你可以利用 Elasticsearch 更多的高级特性，它的整个引擎是可配置并且灵活的。
从众多高级特性中，挑选恰当去修饰的 Elasticsearch，使它能解决你本地遇到的问题。

你可以 ((("Apache 2 license"))) 免费下载，使用，修改 Elasticsearch。它在 http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2 license] 协议下发布的，
这是众多灵活的开源协议之一，Elasticsearch 的源码被托管在 Github 上 https://github.com/elastic/elasticsearch[github.com/elastic/elasticsearch]。快来
查看 https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md[Contributing to Elasticsearch]，如果你想加入我们这个令人惊奇的 contributors 团体。

如果你对 Elasticsearch 有任何相关的问题，包括特定的特性(specific features)，语言客户端(language clients)和插件(plugins)，
可以加入这里 https://discuss.elastic.co[discuss.elastic.co]。

***************************************
.The Mists of Time
***************************************

许多年前，一个刚结婚的名叫 Shay Banon 的失业开发者，跟着他的妻子去了伦敦，他的妻子在那里学习厨师。
在寻找一个赚钱的工作的时候，为了给他的妻子做一个食谱搜索引擎，他开始使用早起的 Lucene。

直接使用 Lucene 是很难的，因此 Shay started 开始做一个抽象层，使用它，Java 开发者可以很简单的给他们的程序添加搜索功能。
他发布了他的第一个开源项目，取名 Compass。

后来 Shay 获得了一份工作，主要是高性能，分布式环境下的内存数据网格。这个对于高性能，实时，分布式搜索引擎的需求尤为突出，
他决定从写 Compass，把它变为一个单机服务器程序，并取名 Elasticsearch。

第一个公开版本在2010年2月发布，从此以后，Elasticsearch 已经成为了 Github 上最活跃的项目之一，他拥有超过300名 contributors(目前691名contributors)。
一家公司已经开始围绕 Elasticsearch 提供商业服务，并开发新的特性，但是，对于所有人来说，Elasticsearch 是并且永远是开源软件。

据说，Shay的妻子还在等着她的食谱搜索引擎...
