[[running-elasticsearch]]
=== 安装并运行 Elasticsearch

想用最简单的方式去理解 Elasticsearch 能为你做什么，那就是使用它了，
让我们开始吧！ ((("Elasticsearch", "installing")))

安装 Elasticsearch 之前，你需要先安装一个较新的版本的 Java，
最好的选择是，你可以从 http://www.java.com[_www.java.com_] 获得官方提供的最新的 Java。

之后，你可以从 elastic 的官网 https://www.elastic.co/downloads/elasticsearch[_elastic.co/downloads/elasticsearch_]
获取最新版本的 Elasticsearch。

要想安装 Elasticsearch，先下载并获取适合你操作系统的 Elasticsearch 版本。假如你想了解更多的信息，
可以查看 Elasticsearch 参考手册里边的安装部分，这边给出的链接指向安装说明 {ref}/_installation.html[Installation]。

[TIP]
====
当你准备将 Elasticsearch 投入到生产环境中的时候，
你可以到在 http://www.elastic.co/downloads/elasticsearch[官网下载地址] 找到 Debian 或者 RPM 包，
除此之外，你也可以使用官方支持的 https://github.com/elasticsearch/puppet-elasticsearch[Puppet module]
或者 https://github.com/elasticsearch/cookbook-elasticsearch[Chef cookbook]。
====

一旦你解压好了归档文件，Elasticsearch 已经准备好运行了。按照下面的操作，在前台(foregroud)启动 Elasticsearch：

[source,sh]
--------------------------------------------------
cd elasticsearch-<version>
./bin/elasticsearch <1> <2>
--------------------------------------------------
<1> 如果你只是想把 Elasticsearch 当作一个守护进程启动，那么可以在后面添加参数 `-d`。
<2> 如果你是在 Windows 上面运行 Elasticseach，你应该运行 `bin\elasticsearch.bat` 而不是 `bin\elasticsearch`。


测试 Elasticsearch 是否启动成功，可以通过打开另一个终端(terminal)，按照下面的做法：

[source,sh]
--------------------------------------------------
curl 'http://localhost:9200/?pretty'
--------------------------------------------------

TIP：如果你是在 Windows 上面运行 Elasticsearch，你可以通过从 http://curl.haxx.se/download.html[`http://curl.haxx.se/download.html`] 下载 cURL。
cURL 给你提供了一种简易的方式去将 requests 提交到 Elasticsearch，并且安装 cURL 之后，你可以通过复制与粘贴去尝试书中的许多例子。

你应该得到和下面类似的响应(response)：

[source,js]
--------------------------------------------------
{
  "name" : "Tom Foster",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.1.0",
    "build_hash" : "72cd1f1a3eee09505e036106146dc1949dc5dc87",
    "build_timestamp" : "2015-11-18T22:40:03Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
--------------------------------------------------
// SENSE: 010_Intro/10_Info.json

经过以上，你现在应该已经起了一个 Elasticsearch 节点了，并且正在运行中，你可以开始使用它做实验了。
一个 _节点_ 是一个运行中的 Elasticsearch 的实例。((("nodes", "defined"))) 而一个 _集群_ 是一组节点
拥有相同的 `cluster.name` ，他们能一起工作并共享数据，还提供容错与扩展。(然而，一个单独的节点也可以组成一个集群。) `elasticseach.yml`
是当你启动一个节点时需要加载的文件，你可以在里面修改 `cluster.name` (译者注：这个重启服务后才会生效)。
关于上面的`cluster.name`以及其它  <<important-configuration-changes, Important Configuration Changes>> 信息，
你可以在这本书的后面章节 Production Deployment 部分找到更多。

TIP：看到下方的 View in Sense 的例子了么？<<sense, Install the Sense console>> 使用你自己的 Elasticsearch 集群去运行这本书中的例子，
查看会有怎样的结果。

当 Elastcisearch 在前台运行时，你可以通过按 Ctrl+C 去停止

[[sense]]
==== 安装 Sense
Sense 是一个 https://www.elastic.co/guide/en/kibana/current/index.html[Kibana] 应用 ((("Sense console", "Kibana app")))
它提供交互式的控制台，通过你的 browser 直接向 Elasticsearch 提交请求。
这本书的在线版本包含有一个 View in Sense 的链接，里面有许多代码示例。当点击的时候，它会打开一个代码示例的Sense控制台。
你不必要安装 Sense，但它通过让你在你本地的 Elasticsearch 集群上头测试示例代码，使这本书的对你而言，更具有交互性。

((("Sense", "downloading and installing"))) 安装与运行 Sense：

. 在 Kibana 目录下运行下面的命令，下载并安装 Sense app：
+
[source,sh]
--------------------------------------------------
./bin/kibana plugin --install elastic/sense <1>
--------------------------------------------------
<1> Windows上面执行: `bin\kibana.bat plugin --install elastic/sense`。
+
NOTE：你可以直接从这里 https://download.elastic.co/elastic/sense/sense-latest.tar.gz 下载 Sense
离线安装可以查看这里 https://www.elastic.co/guide/en/sense/current/installing.html#manual_download[install it on an offline machine] 。

. Start Kibana.
+
[source,sh]
--------------------------------------------------
./bin/kibana <1>
--------------------------------------------------
<1> Windows上启动kibana: `bin\kibana.bat`。

. 在你的浏览器中打开 Sense： `http://localhost:5601/app/sense` 。
